spring:
  application:
    name: food-delivery-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    ssl:
      verify-hostname: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: 9090
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always
